Revert "Ensure the latest version of NPM is installed"
This reverts commit 3183975274011f1c826ecf3f406601259e3cde5e.

It wasn't working anymore on Docker for Mac:

    module.js:340
    throw err;
          ^
        Error: Cannot find module 'semver'